# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-05-20 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/banner/')),
            ],
            options={
                'verbose_name_plural': 'banner信息',
                'db_table': 'banner',
            },
        ),
        migrations.CreateModel(
            name='DishesList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.IntegerField(choices=[(0, '早餐'), (1, '午餐'), (2, '晚餐')])),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '菜品选择',
                'db_table': 'dishes_list',
            },
        ),
        migrations.CreateModel(
            name='DishesType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('image', models.ImageField(upload_to='media/type/')),
            ],
            options={
                'verbose_name_plural': '菜品信息',
                'db_table': 'dishes_type',
            },
        ),
        migrations.CreateModel(
            name='ReserveStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=32)),
                ('status', models.IntegerField(choices=[(0, '未预定'), (1, ' 已预订')], default=0)),
                ('create', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '预订信息',
                'db_table': 'reserve',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('openid', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.CharField(blank=True, max_length=400, null=True)),
                ('role', models.IntegerField(choices=[(0, '员工'), (1, '厨师')], default=0)),
            ],
            options={
                'verbose_name_plural': '用户信息',
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='reservestatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='meal.UserInfo'),
        ),
        migrations.AddField(
            model_name='disheslist',
            name='dishes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list', to='meal.DishesType'),
        ),
    ]
