# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-05-21 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0002_formid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservestatus',
            name='create',
            field=models.DateField(auto_now=True),
        ),
    ]
