# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-05-21 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0003_auto_20190521_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banner/'),
        ),
        migrations.AlterField(
            model_name='dishestype',
            name='image',
            field=models.ImageField(upload_to='type/'),
        ),
    ]
