# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-05-24 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0005_auto_20190522_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemindTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast_time', models.CharField(max_length=100, verbose_name='早餐时间')),
                ('lunch_time', models.CharField(max_length=100, verbose_name='午餐时间')),
                ('dinner_time', models.CharField(max_length=100, verbose_name='晚餐时间')),
            ],
            options={
                'verbose_name_plural': '提醒时间',
                'db_table': 'remind_time',
            },
        ),
        migrations.CreateModel(
            name='TemplateReceiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='template', to='meal.UserInfo', verbose_name='消息接收人')),
            ],
            options={
                'verbose_name_plural': '模板消息接收者',
                'db_table': 'template',
            },
        ),
    ]
