# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-05-28 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0006_remindtime_templatereceiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishestype',
            name='types',
            field=models.IntegerField(choices=[(0, '健康早点'), (1, '时令小炒'), (2, '养生煲汤'), (3, '家庭小炒'), (4, '百搭配菜'), (5, '经典硬菜')], default=0),
        ),
    ]
