# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-05-28 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0007_dishestype_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishestype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='type/'),
        ),
    ]
