# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-05-30 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0008_auto_20190528_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservestatus',
            name='create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
